import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const themesDir = path.resolve(__dirname, '../src/themes');
const outputFile = path.resolve(__dirname, '../extension/baked_themes.js');

function buildThemes() {
  console.log('Building baked themes...');
  let bakedThemes = [];
  
  if (fs.existsSync(themesDir)) {
    const files = fs.readdirSync(themesDir);
    for (const file of files) {
      if (file.endsWith('.css')) {
        const filePath = path.join(themesDir, file);
        const content = fs.readFileSync(filePath, 'utf8');
        bakedThemes.push(content);
        console.log(`  -> Included ${file}`);
      }
    }
  }

  const jsContent = `// Auto-generated by scripts/build-themes.js
// Do not edit this file directly. Place your CSS files in src/themes/ instead.

const MATUFLOW_BAKED_THEMES = ${JSON.stringify(bakedThemes, null, 2)};

if (typeof window !== 'undefined') {
  window.MATUFLOW_BAKED_THEMES = MATUFLOW_BAKED_THEMES;
}
`;

  fs.writeFileSync(outputFile, jsContent, 'utf8');
  console.log(`Successfully built ${bakedThemes.length} themes into extension/baked_themes.js`);
}

buildThemes();
